version: '3'

services:
  movie-review-categorizer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./results:/app/results
      - ./reports:/app/reports
    environment:
      - PYTHONUNBUFFERED=1
